### ISSUE TITLE
Not sure how to do this

### ISSUE THREAD

**Issue by jfberhane** [Bucknell-Biol364/Biology205tutorial#12]
https://github.com/Bucknell-Biol364/Biology205tutorial/blob/4148fe6c19e0171ca776abb4bc269973ea3d5b68/Rscript%20document.R#L191

@jssimpson20 You should make sure to direct the students to use the Adjusted R-squared and not the Multiple R-squared because they both show up when you run summary(lm1). And I can't figure out how to print both the regression line equation and the R-squared. I tried adding a second geom_text line under the first one that had different x,y coordinates and a new label but it didn't work and only showed the line equation. So then I tried adding it to what's in parentheses for the first geom_text with the two separated by commas but that didn't work and only printed the line equation. If the student has to have both the line equation and the R-squared on the plot, how would they do that?

**Comment by jssimpson20** [comment]
@chadsussman do you have any ideas?

**Comment by chadsussman** [comment]
Thanks for the note, good call to ask for the adjusted R-square instead of the other one. I tried to edit the geom_text and I think it works: geom_text(x = 0.4, y=0.9, label="y = 1.105x + -0.1665  R^2=0.979")
So I guess the important thing is to keep the text within the quotes too. Perhaps putting a key for that section somewhere in the repository may be a good idea

**Comment by jfberhane** [comment]
@jssimpson20 @chadsussman Ohhhh ok. I didn't even think that you should put it with the equation. I thought it would be on the plot somewhere else away from the equation almost like it was a second text box. That make sense for them to be together like that
