### ISSUE TITLE
Ready for peer review

### ISSUE THREAD

**Issue by jssimpson20** [Bucknell-Biol364/Biology205tutorial#5]
https://github.com/Bucknell-Biol364/Biology205tutorial/blob/14b813bfd6c1a3b3eb3a761b659d97bd6e0fe189/Rscript%20document.R#L1

@cheyennelmoore 
@jfberhane 
@kme012 
@KField-Bucknell 

Hi everyone, we're ready for peer review. Thank you!

**Comment by cheyennelmoore** [comment]
Hey hey! Looks great! Julie gave really thorough comments and caught most everything I found. The only thing I might change is the code on line 19 is a bit long, so I might split it between 2 lines. Good job!

**Comment by kme012** [comment]
This looks really good. You guys do a good job explaining everything, and I like how you build the standard curve bit by bit. I mostly found some things that didn't appear where you said they would (at least on my computer), but that could just be my computer being weird.

- Line 19: The summary stats appear in the console but it's the bottom left panel for me.
- Line 55: Small thing but it made me pause for a moment - if you're lazy like I am and just read the excel file in without doing the File -> import step, no tab automatically opens. Printing the excel file also doesn't open it in a new tab (just makes the data appear in the console), so if you have someone  running through it like I did, then mentioning the tab above could be a little confusing.
- Line 56: Comment stretches off the screen a little
- Line 62 and Line 67: I think Julie mentioned this, but the paragraphs repeat here.
- In our tips section, we mentioned using internet resources for help, which is implied in yours - but since this is their first exposure to R and potentially programming at all, maybe mentioning some specific websites to point them in the the right direction would be useful?
- Finally, just aesthetics-wise - if you wanted the all caps section titles to stand out in a different color, you could use * * on either side instead of the ##
